### ISSUE TITLE
use std::source_location

### ISSUE THREAD

**Issue by angeletakis** [renatoGarcia/icecream-cpp#15]
C++20 has the [std::source_location](https://en.cppreference.com/w/cpp/utility/source_location) which replaces the need for macros.

**Comment by renatoGarcia** [comment]
This only partially would provide the current macro features. While `std::source_location` would get rid of [`__FILE__`, `__LINE__`, and `ICECREAM_FUNCTION`](https://github.com/renatoGarcia/icecream-cpp/blob/0f77e26731835941c300e14dbe3b0fd0f45343ba/icecream.hpp#L80), unfortunately there is no way of get the variables names without `#__VA_ARGS__`.
