### ISSUE TITLE
avoid using the _() macro/function which used for text translation in other libraries

### ISSUE THREAD

**Issue by asmwarrior** [renatoGarcia/icecream-cpp#18]
Hi, I try to use the header file, but it reported a build error.

I see that in some of my header file, the `_()` is defined to text translation. (For example, under wxWidgets, the `_()` is defined as:

~~~~
 #define _(s)                               wxGetTranslation((s))
~~~~

While, I see in the icecream.hpp, it also define some function like:

~~~~
    template<typename... Ts>
    auto _(std::string const& fmt, Ts&&... vs) -> detail::FormatterPack<decltype(std::forward<Ts>(vs))...>
    {
        return detail::FormatterPack<decltype(std::forward<Ts>(vs))...>{fmt, std::forward<Ts>(vs)...};
    }
~~~~

So, I would like to find a way to solve such conflict issue. Thanks.

**Comment by renatoGarcia** [comment]
Hi @asmwarrior.
Oh, I was not expecting `_ ` being a macro. For sure, `_` being very commonly used to text translation, it has a use precedence there. I will rename it to `f_`.
Thanks!

**Comment by asmwarrior** [comment]
Thanks for the fix.
