### ISSUE TITLE
Simplest way to print function called with the arguments that were passed

### ISSUE THREAD

**Issue by vadi2** [renatoGarcia/icecream-cpp#27]
What is the simplest way to print function called with the arguments that were passed? I'm debugging an interface implementation, so I don't have so much control over who is calling me methods; rather I am on the receiving end of them being called.

I can add `IC()` at the beginning of a function to see its name and arguments, but the argument values themselves aren't printed.

**Comment by vadi2** [comment]
That does work, but it then doesn't say which function was called unlike IC() by itself. I see that there's a config toggle for prefixing the function called to all output - perhaps that is the best way?

**Comment by renatoGarcia** [comment]
Oh, sure. So you are right. You will need call

    icecream::ic.include_context(true);

With that all calls to IC* macros all around the code will print the source name, line number, and function signature.

You gave me a new idea. Maybe a way to print the context along with the values would be nice. Let's say something at the lines of

    IC(IC_CTX, foo, bar)
    IC_CTX(foo, bar)

Food for thought.

**Comment by vadi2** [comment]
Did this end up making it in?

**Comment by renatoGarcia** [comment]
Hi @vadi2. Not yet, but it is on my roadmap. I just need find some free time to put the work on.
I will go with the IC_CTX(...) option.
