### ISSUE TITLE
Use __builtin_dump_struct on clang 8+ ?

### ISSUE THREAD

**Issue by htfy96** [renatoGarcia/icecream-cpp#3]
On Clang 8+, __builtin_dump_struct pretty prints a struct variable without any manual boilerplate. 
 See https://stackoverflow.com/a/58721823/4140668

**Comment by renatoGarcia** [comment]
I didn't knew about that function. It surely will be a great addition to print structs that don't have a `operator<<` overload, a code that otherwise wouldn't compile. Thanks for the suggestion!
